config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import password_change, password_change_done
from django.views.generic import TemplateView
from django.views import defaults as default_views

from mercatitulo import views as views_home
from mercatitulo.derechos import views as views_derechos
from mercatitulo.proyectos import views as views_proyectos
from mercatitulo.users import views as views_users
from mercatitulo.contacto import views as views_contacto

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^password-change/$', password_change, {
        'template_name': 'registration/password_change_form.html'},
        name='password_change'),
    url(r'^password_change_done/$', password_change_done, {
        'template_name': 'registration/password_change_done.html'}, 
        name='password_change_done'),
    url(r'^users/', include('mercatitulo.users.urls', namespace='users')),
    url(r'^accounts/signup/', views_users.SignupMercatitulo.as_view(), name='signup'),
    url(r'^accounts/login/', views_users.LoginMercatitulo.as_view(), name='login'),
    url(r'^mi-cuenta/$', views_users.MiCuenta, name='mi_cuenta'),    
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', views_home.Logout, name='logout'),

    # Tinymce
    url(r'^tinymce/', include('tinymce.urls')),

    # Your stuff: custom urls includes go here
    url(r'^$', views_home.Landing, name="landing"),
    url(r'^home2$', views_home.Home, name="home"),
    url(r'^quienes-somos/',
        TemplateView.as_view(template_name="pages/quienes_somos.html"), name='quienes'),
    url(r'^mercado-derechos/$', views_derechos.Mercado, name='mercado'),
    url(r'^mercado-derechos/(?P<slug>[\w-]+)/$', views_derechos.Detalle, name='derecho_detalle'),
    url(r'^nuevos-proyectos/$', views_proyectos.Proyectos, name='proyectos'),
    url(r'^proyecto/confirmacion/$', views_proyectos.Confirmacion, name='proyecto_confirmacion'),

    # Vender
    url(r'^vender/$', views_derechos.Vender, name='vender'),
    url(r'^vender/proyecto_nuevo/$',
        views_proyectos.NuevoProyecto, name='nuevo_proyecto'),
    url(r'^vender/confirmacion/$', views_derechos.Confirmacion, name='confirmacion'),

    # Comprar
    url(r'^comprar/$', views_derechos.Comprar, name='comprar'),
    url(r'^ofertar/(?P<slug>[\w-]+)/$', views_derechos.Ofertar, name='ofertar'),
    url(r'^save-oferta/$', views_derechos.SaveOferta, name='save-oferta'),
    url(r'^save-oferta/(?P<llave>[-:\w]+)/$', views_derechos.ConfirmOferta, name='confirm-oferta'),
    url(r'^detalle-compra/$', views_derechos.detalleCompra, name='detalle-compra'),
    # Ajax
    url(r'^ajax/load_proyectos/$',
        views_proyectos.LoadProyectos, name='load_proyectos'),

    #Editar eliminar proyectos
    url(r'^proyecto/editar/(?P<slug>[\w-]+)/$', views_proyectos.EditarProyectos, name='editar_proyecto'),
    url(r'^proyecto/eliminar/(?P<slug>[\w-]+)/$', views_proyectos.EliminarProyectos, name='eliminar_proyecto'),

    #Editar eliminar derechos
    url(r'^derechos/editar/(?P<slug>[\w-]+)/$', views_derechos.EditarDerechos, name='editar_derecho'),
    url(r'^derechos/eliminar/(?P<slug>[\w-]+)/$', views_derechos.EliminarDerechos, name='eliminar_derecho'),

    #Contacto
    url(r'^contacto/$', views_contacto.Contacto, name='contacto'),

    #Compania
    url(r'^derechos-que-son/$', TemplateView.as_view(template_name='pages/derechos_que_son.html'), name='derechos_que_son'),
    url(r'^como-funciona/$', TemplateView.as_view(template_name='pages/como_funciona.html'), name='como_funciona'),
    url(r'^riesgos-beneficios/$', TemplateView.as_view(template_name='pages/riesgos_beneficios.html'), name='riesgos_beneficios')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

mercatitulo/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mercatitulo/aliados/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Aliado(models.Model):
    """Clase para hacer administrables los proyectos"""
    nombre = models.CharField(max_length=255)
    foto = models.ImageField(upload_to='aliado')
    posicion = models.FloatField(default=0)

    def __str__(self):
        return self.nombre

mercatitulo/derechos/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from autoslug import AutoSlugField
from tinymce.models import HTMLField


from mercatitulo.proyectos.models import Proyecto


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

NEGOCIABLE = (
    ('0', 'No'),
    ('1', 'Si'),
)

FRECUENCIA = (
    ('1', 'Anual'),
    ('12', 'Mensual'),
    ('6', 'Cada dos meses'),
    ('4', 'Cada tres meses'),
    ('2', 'Cada seis meses'),
)

ESTADOS = (
    ('0', 'Por aprobar'),
    ('1', 'Aprobado'),
    ('2', 'En proceso de compra'),
    ('3', 'Eliminado por el usuario'),
    ('4', 'Comprado'),
)

ESTADOS_OFERTAS = (
    ('0', 'En estudio'),
    ('1', 'Aceptada'),
    ('2', 'Rechazada'),
)

@python_2_unicode_compatible
class Derecho(models.Model):
    """Clase para gestionar los titulos fiduciarios"""
    nombre = models.CharField(
        max_length=140, verbose_name='Nombre del anuncio')
    proyecto = models.ForeignKey(
        Proyecto, default=None, verbose_name='Proyecto/Inmueble', limit_choices_to={'estado': 1})
    precio = models.FloatField(default=None, verbose_name='Precio de venta')
    precio_minimo = models.FloatField(
        default=None, verbose_name='Precio de venta minimo')
    monto_dividendo = models.FloatField(default=None)
    rentabilidad = models.FloatField(default=None, null=True)
    frecuencia_pago = models.CharField(
        max_length=2, choices=FRECUENCIA, default=1)
    ultimo_rendimiento = models.FloatField(default=None)
    negociable = models.CharField(
        max_length=1, choices=NEGOCIABLE, default=0)
    descripcion = HTMLField()
    autor = models.ForeignKey(AUTH_USER_MODEL, default=None, null=True)
    fecha_creacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(
        max_length=1, choices=ESTADOS, default=0)
    slug = AutoSlugField(populate_from='nombre', null=True, editable=False, unique=True)

    def __str__(self):
        return self.nombre

@python_2_unicode_compatible
class Compras(models.Model):
    id_derecho = models.CharField(max_length=255)
    derecho = models.ForeignKey(
        Derecho, default=None, verbose_name='Nombre del derecho')
    valor_derecho = models.FloatField(default=None, 
        verbose_name='Valor venta del derecho')
    id_proyecto = models.CharField(max_length=255)
    proyecto = models.CharField(max_length=255, verbose_name='Nombre del proyeto')
    valor_proyecto = models.FloatField(default=None)
    comprador = models.ForeignKey(AUTH_USER_MODEL, 
        related_name='usuario_comprador', default=None, null=True)
    correo_comprador = models.CharField(max_length=255, verbose_name='Correo del comprador')
    telefono_comprador = models.CharField(max_length=255, verbose_name='Telefono del comprador')
    vendedor = models.ForeignKey(AUTH_USER_MODEL, 
        related_name='usuario_vendedor', default=None, null=True)
    correo_vendedor = models.CharField(max_length=255, verbose_name='Correo del vendedor')
    telefono_vendedor = models.CharField(max_length=255, verbose_name='Telefono del vendedor')

    class Meta:
        verbose_name = 'Compras realizadas'
        verbose_name_plural = 'Compras realizadas'

    def __str__(self):
        return self.derecho.nombre

@python_2_unicode_compatible
class Ofertas(models.Model):
    autor = models.ForeignKey(AUTH_USER_MODEL, default=None, null=True)
    correo = models.CharField(max_length=255, verbose_name='Correo del usuario')
    telefono = models.CharField(max_length=255, verbose_name='telefono del usuario')
    derecho = models.ForeignKey(
        Derecho, default=None, limit_choices_to={'estado': 1})
    valor = models.FloatField(default=None, verbose_name='Valor de la oferta')
    estado = models.CharField(
        max_length=1, choices=ESTADOS_OFERTAS, default=0)
    llave = models.CharField(max_length=64, unique=True)

    class Meta:
        verbose_name = 'Ofertas por derecho'
        verbose_name_plural = 'Ofertas por derechos'

    def __str__(self):
        return self.derecho.nombre

@python_2_unicode_compatible
class GaleriaMercado(models.Model):
    """Clase para hacer administrables los testimonios"""
    titulo = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    foto = models.ImageField(upload_to='galeria')

    def __str__(self):
        return self.titulos

mercatitulo/contacto/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions

from .models import Contacto

class ContactoForm(forms.ModelForm):
	class Meta:
		model = Contacto
		fields = [
			'nombre',
			'telefono',
			'correo',
			'mensaje',
		]

	def __init__(self, *args, **kwargs):
		super(ContactoForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper(self)
		self.helper.layout.append(
			FormActions(Submit('save', 'Enviar'),)
		)

mercatitulo/aliados/views.py
from django.shortcuts import render

# Create your views here.

mercatitulo/contacto/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from .forms import ContactoForm
from mercatitulo.users.models import User
from mercatitulo.derechos.utils import Send_mail


def Contacto(request):
	if request.method == "POST":
		form = ContactoForm(request.POST)
		if form.is_valid():
			nuevo_contacto = form.save()
			usuarios_correo = User.objects.filter(is_staff=True)
			destino_correo = []
			for usuario in usuarios_correo:
				destino_correo.append(str(usuario.email))
			Send_mail(
				{ 
					'contacto_name': nuevo_contacto.nombre,
					'contacto_email': nuevo_contacto.correo,
					'contacto_tel': nuevo_contacto.telefono,
				},
				destino_correo,
				'partials/email/nuevo_contacto_admin.txt',
				'partials/email/nuevo_contacto_admin.html',
				'Nuevo Contacto',
			)
			return render(request, 'pages/contacto_confirmar.html')
	else:
		form = ContactoForm()
	return render(request, 'forms/contacto.html', {'form': form})

mercatitulo/documentos/views.py
from django.shortcuts import render

# Create your views here.

mercatitulo/fiduciarias/views.py
from django.shortcuts import render

# Create your views here.

mercatitulo/proyectos/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from mercatitulo.proyectos.forms import NuevoProyectoForm, BuscarProyectoForm, EditarProyectoForm
from mercatitulo.proyectos.models import Proyecto, TipoProyecto, ESTADOS as estado_proyecto
from mercatitulo.derechos.utils import Cast, Send_mail
from mercatitulo.users.models import User



def LoadProyectos(request):
	""" Vista ajax que carga el select de proyectos segun criterios """
	if 'tipo' in request.GET.keys() and 'marca' in request.GET.keys():
		try:
			exclude = request.GET['exclude']
			tipo_id = request.GET['tipo']
			marca_id = request.GET['marca']
			proyectos = Proyecto.objects.filter(
				tipo=tipo_id, marca=marca_id, estado=1).values()
		except ObjectDoesNotExist:
			proyectos = False

		data = {
			'proyectos': proyectos,
			'exclude': exclude,
		}
		return render(request, 'ajax/proyectos_sel.html', {'data': data})
	else:
		return HttpResponse("No hay nada que ver")

def EliminarProyectos(request, slug):
	proyecto = get_object_or_404(Proyecto, slug=slug)
	data = {
        'proyecto': proyecto,
    }
	if request.method == "POST":
		proyecto.delete()
		messages.success(request, 'El proyecto ha sido eliminado')
		redirect_to = '/mi-cuenta/?opc=proyectos'
		return redirect(redirect_to)
	else:
		return render(request, 'pages/eliminar_proyectos.html', {'data': data})

def EditarProyectos(request, slug):
	proyecto = get_object_or_404(Proyecto, slug=slug)
	data = {
        'proyecto': proyecto,
    }
	if request.method == "POST":
		post = request.POST.copy()
		if not post['precio'] == '$ 0':
			post['precio'] = Cast(post['precio'])
		if not post['rendimiento'] == '$ 0':
			post['rendimiento'] = Cast(post['rendimiento'])
		form = EditarProyectoForm(post, request.FILES, instance=proyecto)
		if form.is_valid():
			form.save()
			messages.success(request, 'El proyecto ha sido modificado')
			redirect_to = '/mi-cuenta/?opc=proyectos'
			return redirect(redirect_to)
	else:
		form = EditarProyectoForm(instance=proyecto)
	return render(request, 'forms/editar_proyecto.html', {'form': form, 'data': data})

def NuevoProyecto(request):
	if request.method == "POST":
		post = request.POST.copy()
		if not post['precio'] == '$ 0':
			post['precio'] = Cast(post['precio'])
		if not post['rendimiento'] == '$ 0':
			post['rendimiento'] = Cast(post['rendimiento'])
		form = NuevoProyectoForm(post, request.FILES)
		if form.is_valid():
			nuevo_proyecto = form.save()
			request.session['proyecto_id'] = nuevo_proyecto.id
			if request.user.is_authenticated():
				proyecto = Proyecto.objects.get(pk=nuevo_proyecto.id)
				proyecto.autor_id = request.user.id
				proyecto.save()
				Send_mail(
					{ 
						'proyecto_id': nuevo_proyecto.id,
						'proyecto_name': nuevo_proyecto.nombre,
						'username': request.user.username,
					},
					[request.user.email],
					'partials/email/asignacion_proyecto.txt',
					'partials/email/asignacion_proyecto.html',
					'Nuevo Proyecto',
				)
				redirect_to = '/proyecto/confirmacion/'
			else:
				redirect_to = '/accounts/signup/'
			usuarios_correo = User.objects.filter(is_staff=True)
			destino_correo = []
			for usuario in usuarios_correo:
				destino_correo.append(str(usuario.email))
			if request.user.username:
				usuario = request.user.username
			else:
				usuario = 'Pendiente asignar usuario'
			Send_mail(
				{ 
					'proyecto_id': nuevo_proyecto.id,
					'proyecto_name': nuevo_proyecto.nombre,
					'username': usuario,
				},
				destino_correo,
				'partials/email/asignacion_proyecto_admin.txt',
				'partials/email/asignacion_proyecto_admin.html',
				'Nuevo Proyecto',
			)
			return redirect(redirect_to)
	else:
		form = NuevoProyectoForm()
	return render(request, 'forms/nuevo_proyecto.html', {'form': form})

def Confirmacion(request):
	if request.session.get('proyecto_id', None):
		proyecto = Proyecto.objects.get(pk=request.session['proyecto_id'])
		del request.session['proyecto_id']
		data = {
			'proyecto': proyecto,
			'estado': dict(estado_proyecto).get(proyecto.estado),
		}
		return render(request, 'pages/proyecto_confirmacion.html', {'data': data})
	else:
		redirect_to = '/'
		return redirect(redirect_to)


def Proyectos(request):
	form = BuscarProyectoForm()
	if 'tipos_proyecto' in request.GET.keys():
		tipos_proyecto_id = request.GET['tipos_proyecto']
		proyectos = Proyecto.objects.filter(estado=1, autor__isnull=False, tipo=tipos_proyecto_id)
	elif 'nombre' in request.GET.keys():
		nombre = request.GET['nombre']
		proyectos = Proyecto.objects.filter(estado=1, autor__isnull=False, nombre=nombre)
	else:
		proyectos = Proyecto.objects.filter(estado=1, autor__isnull=False)
	tipos_de_proyecto = TipoProyecto.objects.all().order_by('nombre')
	data = {
		'proyectos': proyectos,
		'tipos_proyecto': tipos_de_proyecto,
		'buscar_proyecto_form': form,
	}
	return render(request, 'pages/proyectos.html', {'data': data})

mercatitulo/testimonios/views.py
from django.shortcuts import render

# Create your views here.

mercatitulo/templates/pages/detalle.html
{% extends "base/base.html" %}

{% load staticfiles thumbnail i18n mathfilters humanize %}
{% load testimonios_tags derechos_tags %}
{% block title %}Mercado de derechos - Mercatitulo{% endblock %}
{% block content %}
  <div class="container">
    <div class="row detalle-derechos">
    	<div class="col-md-6">
    		<img src="{{ data.derechos.proyecto.foto|thumbnail_url:'proyectos' }}" class="img-responsive" alt="{{ derechos.nombre }}">
    	</div>
    	<div class="col-md-6 detalle">
        <div class="col-md-12 tipos">
      		{% for tipo in data.derechos.proyecto.tipo.all %}
            <p> {{ tipo }} </p>
          {% endfor %}
        </div>
        <div class="col-md-12 derecho-nombre">
    		  <p> {{ data.derechos.nombre }} </p>
        </div>
        <div class="col-md-12 inversion">
          <p> Precio de venta del derecho fiduciario </p> 
        </div>  
        <div class="col-md-6 precio">
          <p> $ {{ data.derechos.precio|floatformat:"0"|intcomma }} </p>
        </div>
        <div class="col-md-6 marca">
          <p> Marca comercial: {{ data.derechos.proyecto.marca }} </p>
        </div>
        <div class="col-md-12">
          <p class="label_partial"> Proyecto inmobiliario </p>
          <p class="proyecto_name"> {{ data.derechos.proyecto.nombre }} </p>
        </div>
        <div class="col-md-12 negociable">
          <div class="col-md-6">
            <p>
              Opción:
              {% if data.derechos.negociable == '1' %}
                Negociable
              {% else %}
                No negociable
              {% endif %} 
            </p>
          </div>
          <div class="col-md-6">
            <p> Rentabilidad: {{ data.derechos.rentabilidad|floatformat:"2"|intcomma }}%</p>
          </div>
          <div class="col-md-12">
            <p>Último rendimiento: $ {{ data.derechos.ultimo_rendimiento|floatformat:"0"|intcomma }}</p>
          </div>
          <div class="col-md-12">
            <p>Monto dividendo: $ {{ data.derechos.monto_dividendo|floatformat:"0"|intcomma }}</p>
          </div>
          <div class="col-md-12">
            <p>Frecuencia de pago: {{ data.derechos.get_frecuencia_pago_display }}</p>
          </div>
        </div>
        {% if data.derechos.estado != '2' %}
          <div class="col-md-12 botones_wrapper">
            <p>
              <form action="{% url 'comprar' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="derecho_id" value="{{ data.derechos.pk }}">
                {% if data.derechos.negociable == '1' %}
                  <a href="{% url 'ofertar' data.derechos.slug %}">
                    <button class="boton" type="button">ofertar</button>
                  </a>
                {% endif %}
                <input type="submit" class="boton" value="Comprar">
              </form>
            </p>
          </div>
        {% else %}
          <p class="btn btn-warning">
            En proceso de Compra
          </p>
        {% endif %}
    	</div>
      <div class="col-md-12 descripcion">
        <h3>Información del título valor</h3>
        <p>{{ data.derechos.descripcion|striptags|safe }}</p>
      </div>
    </div>
  </div>
  <div class="container proceso_compra">
    <h2>Proceso de compra</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacus sem, pellentesque quis enim in, laoreet pulvinar quam. Aenean quis fermentum lectus. Pellentesque pretium, sem eu dignissim cursus, elit turpis rutrum velit, vitae elementum purus odio laoreet felis. Nam ex mauris, maximus sed lectus efficitur, fermentum dapibus eros. Aliquam tristique justo eget tristique ultrices. Nulla magna arcu, finibus ac tellus et, cursus tempus leo. Vestibulum ut urna ex. Mauris in lobortis libero, et imperdiet turpis. Praesent a quam viverra, suscipit nisi sed, condimentum nunc. Phasellus at risus efficitur, imperdiet lacus ac, volutpat mi. Fusce lacinia enim lorem, eget laoreet orci scelerisque eu. Aenean hendrerit lacus at ipsum condimentum sollicitudin sed iaculis elit. Aliquam metus diam, lobortis convallis tellus ac, pulvinar sagittis elit. Morbi ultricies ultrices enim sit amet imperdiet. Vivamus sodales ligula felis, sed ultricies eros lobortis a.</p>
  </div>

  {% include "partials/cifras.html" %}
  {% lista_testimonios %}

{% endblock %}

mercatitulo/templates/pages/eliminar_proyectos.html
{% extends "base/base.html" %}

{% load staticfiles thumbnail i18n mathfilters humanize %}
{% load testimonios_tags derechos_tags %}
{% block title %}Eliminar Proyecto - Mercatitulo{% endblock %}
{% block content %}

	<div class="container">
		<div class="row confirmacion">
			<h1>Eliminar Proyecto</h1>
			<div class="col-md-12 clearfix">
				<h2>{{ data.proyecto.nombre }}</h2>
				<img src="{{ data.proyecto.foto.url }}" alt="{{ data.proyecto.nombre }}">
				<div class="row datos clearfix">
					<p><strong>Código del Proyecto:</strong> {{ data.proyecto.pk }} </p>
					<p><strong>Precio:</strong> $ {{ data.proyecto.precio|floatformat:"0"|intcomma }} </p>
					<p><strong>Monto rentado:</strong> $ {{ data.proyecto.rendimiento|intcomma }} </p>
					<p><strong>Estado:</strong> {{ data.proyecto.get_estado_display }} </p>
				</div>
			</div>
			<div class="col-xs-12 col-md-12 botones_centro">
                <form method="POST">
                	{% csrf_token %}
                	<a role="button" class="btn btn-default" href="{% url 'mi_cuenta' %}">Cancelar</a>
                	<input class="btn orange" type="submit" value="Eliminar">  
                </form>
            </div>
		</div>
	</div>

	{% include "partials/cifras.html" %}
	{% lista_testimonios %}

{% endblock %}

mercatitulo/templates/pages/oferta_aceptada.html
{% extends "base/base.html" %}

{% load staticfiles thumbnail i18n mathfilters humanize %}
{% load testimonios_tags derechos_tags %}
{% block title %}Confirmar Compra - Mercatitulo{% endblock %}
{% block content %}

	<div class="container">
		<h1>Oferta aceptada</h1>
	</div>

	{% include "partials/cifras.html" %}
	{% lista_testimonios %}

{% endblock %}

mercatitulo/templates/pages/proyectos.html
{% extends "base/base.html" %}

{% load i18n %}
{% load crispy_forms_tags thumbnail humanize %}
{% load testimonios_tags %}
{% block title %}Mercado de derechos - Mercatitulo{% endblock %}
{% block content %}
  <div class="container">
    <h1>Proyectos Inmobiliarios</h1>
    <div class="row main-content no-padding">
    	<div class="col-sm-3 filtros">
    		<h2 class="filtro-titulo">
				Encuentra el tipo de proyecto que estás buscando
			</h2>
			<div class="tipo-titulo">
				{% if data.tipos_proyecto %}
					<ul>
						<li>
							<a href="/nuevos-proyectos/">
								Todos<i class="fa fa-chevron-right" aria-hidden="true"></i>
							</a>
						</li>
						{% for tipo_de_proyecto in data.tipos_proyecto %}
							<li>
								<a href="/nuevos-proyectos/?tipos_proyecto={{ tipo_de_proyecto.id }}">
									{{ tipo_de_proyecto.nombre }}<i class="fa fa-chevron-right" aria-hidden="true"></i>
								</a>
							</li>
						{% endfor %}							
					</ul>
				{% else %}
					<div class="no-content">
						<h2>NO SE HA CARGADO LA GALERÍA</h2>
					</div>
				{% endif %}
			</div>
    	</div>
    	<div class="col-sm-9">
    		<div class="col-md-12">
				{% crispy data.buscar_proyecto_form %}
			</div>
			<div class="clearfix proyectos_mercado">
				{% if data.proyectos %}
					{% for proyecto in data.proyectos %}
						<div class="col-md-12">
							<div class="col-md-12">
								<h2>{{ proyecto.nombre }}</h2>
								<img src="{{ proyecto.foto|thumbnail_url:'proyectos' }}" alt="{{ proyecto.nombre }}">	
								<div class="col-md-12 datos">
									<p>Código: {{ proyecto.id }}</p>
									<p>Precio: ${{ proyecto.precio|floatformat:"0"|intcomma }}</p>
									<p>Rentabilidad estimada: {{ proyecto.rendimiento|intcomma }}%</p>
									<p>Estado: {{ proyecto.get_estado_display }}</p>
								</div>
							</div>
							<div class="col-md-12 descripcion">
								<h4>Descripción</h4>
								<p>{{ proyecto.descripcion|striptags|safe }}</p>
							</div>
							<div class="col-md-6">
								<a href="/mercado-derechos/?proyecto={{ proyecto.id }}&codigo=&tipos_proyecto=&enviar=Buscar" class="btn btn-warning">Ver mas</a>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<div class="no-content">				
						<h1>NO SE ENCONTRARON PROYECTOS</h1>
					</div>
				{% endif %}	
			</div>
    	</div> 
    </div>
  </div>

  {% include "partials/cifras.html" %}
  {% lista_testimonios %}

{% endblock %}